
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



var evenArr = [2 ]

const problemTwo = (arr) => {

	var lastArrs = arr[arr.length - 1] + arr[arr.length - 2];
	var newarr = arr.push(lastArrs);

  if(lastArrs % 2){
    // Do nothing if there is a remainded
  } else{
    evenArr.push(lastArrs)
  }

	if( lastArrs < 4000000){
		problemTwo(arr)
	} else{
    console.log('Even numbers Arr - ', evenArr )
    let totalEvenNums = evenArr.reduce(function(a, b){ return a + b})
    console.log('Total of Even numbers - ', totalEvenNums )
  }
}




module.exports = problemTwo
